version: '3.9'

services:
  pythonapp:
    container_name: cl-pythonapp-container
    image: cl-backend
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres 
      #DATABASE_URL=postgresql:///concha_labs
      
    depends_on:
      - db
  
  db:
    container_name: db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: {}